/*
 * B1 curriculum units (8). Moves from A2's everyday past/future into the grammar
 * that lets a learner reason, hypothesise and connect ideas: the futur simple,
 * the conditionnel, si-clauses, the subjonctif, relative pronouns, the
 * plus-que-parfait, reported speech, and the gérondif + logical connectors.
 * Same authoring model as a1.ts/a2.ts: lessons + vocab + sentences, with a few
 * hand-authored cloze drills where the grammar needs targeting.
 */

import type { UnitDef } from './types';

export const b1Units: UnitDef[] = [
  {
    level: 'B1',
    slug: 'b1-futur-simple',
    title_en: 'The Future: Le Futur Simple',
    title_fr: 'Le futur simple',
    theme: 'grammar',
    grammar_focus: 'futur simple; regular and irregular stems',
    description:
      'Talk about the future the way the French write and speak formally. Learn the futur simple, its one set of endings, and the common irregular stems.',
    lessons: [
      {
        type: 'grammar',
        title: 'Forming the futur simple',
        body_markdown: [
          '## One stem, one set of endings',
          '',
          'The **futur simple** ("I will speak") adds a single set of endings to a stem. For most verbs the stem is the **infinitive** (drop the final **-e** of *-re* verbs):',
          '',
          '- je parler**ai** — I will speak',
          '- tu parler**as** — you will speak',
          '- il/elle parler**a** — he/she will speak',
          '- nous parler**ons** — we will speak',
          '- vous parler**ez** — you will speak',
          '- ils/elles parler**ont** — they will speak',
          '',
          'Notice the endings are the present tense of **avoir** (ai, as, a, -ons, -ez, ont) — a handy memory hook.',
          '',
          '## Common irregular stems',
          '',
          'The endings never change, but some very frequent verbs have a special stem:',
          '',
          '- être → **ser-** · avoir → **aur-** · aller → **ir-** · faire → **fer-**',
          '- venir → **viendr-** · pouvoir → **pourr-** · devoir → **devr-**',
          '- vouloir → **voudr-** · voir → **verr-** · savoir → **saur-** · falloir → **faudr-**',
          '',
          '`Je serai là.` (I will be there.) · `Il fera beau.` (The weather will be nice.)',
          '',
          '## Futur simple vs futur proche',
          '',
          'The **futur proche** (`aller` + infinitive) is for near, planned actions in speech; the **futur simple** is for more distant, formal, or hypothetical futures. Both are correct — `je vais partir` and `je partirai` both mean "I will leave".',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Talking about the future',
        body_markdown:
          'Verbs and time expressions you will use to talk about what comes next.',
      },
    ],
    vocab: [
      {
        lemma_fr: "l'avenir",
        translation_en: 'the future',
        pos: 'noun',
        gender: 'm',
        ipa: 'lavniʁ',
      },
      { lemma_fr: 'demain', translation_en: 'tomorrow', pos: 'adverb', ipa: 'dəmɛ̃' },
      { lemma_fr: 'bientôt', translation_en: 'soon', pos: 'adverb', ipa: 'bjɛ̃to' },
      { lemma_fr: 'plus tard', translation_en: 'later', pos: 'phrase', ipa: 'ply taʁ' },
      { lemma_fr: 'un jour', translation_en: 'one day', pos: 'phrase', ipa: 'œ̃ ʒuʁ' },
      {
        lemma_fr: 'la semaine prochaine',
        translation_en: 'next week',
        pos: 'phrase',
        ipa: 'la səmɛn pʁɔʃɛn',
      },
      { lemma_fr: 'devenir', translation_en: 'to become', pos: 'verb', ipa: 'dəvniʁ' },
      { lemma_fr: 'réussir', translation_en: 'to succeed', pos: 'verb', ipa: 'ʁeysiʁ' },
      { lemma_fr: 'voyager', translation_en: 'to travel', pos: 'verb', ipa: 'vwajaʒe' },
      { lemma_fr: 'changer', translation_en: 'to change', pos: 'verb', ipa: 'ʃɑ̃ʒe' },
      {
        lemma_fr: 'un projet',
        translation_en: 'a plan / project',
        pos: 'noun',
        gender: 'm',
        ipa: 'œ̃ pʁɔʒɛ',
      },
      { lemma_fr: 'peut-être', translation_en: 'maybe', pos: 'adverb', ipa: 'pøtɛtʁ' },
    ],
    sentences: [
      {
        text_fr: 'Un jour, je parlerai français couramment.',
        text_en: 'One day, I will speak French fluently.',
      },
      {
        text_fr: 'Demain, il fera beau et nous sortirons.',
        text_en: 'Tomorrow it will be nice and we will go out.',
      },
      {
        text_fr: 'La semaine prochaine, elle commencera un nouveau travail.',
        text_en: 'Next week she will start a new job.',
      },
      {
        text_fr: 'Nous voyagerons en Italie cet été.',
        text_en: 'We will travel to Italy this summer.',
      },
      {
        text_fr: 'Tu réussiras si tu travailles.',
        text_en: 'You will succeed if you work.',
      },
      {
        text_fr: 'Ils viendront nous voir bientôt.',
        text_en: 'They will come to see us soon.',
      },
      { text_fr: 'Je serai médecin plus tard.', text_en: 'I will be a doctor later.' },
      {
        text_fr: 'Est-ce que vous aurez le temps demain ?',
        text_en: 'Will you have time tomorrow?',
      },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: 'Demain, je ____ mes amis. (voir → futur)',
        answer: 'verrai',
        accepted_alternatives: ['verrai'],
      },
      {
        type: 'cloze',
        prompt: "Nous ____ en France l'année prochaine. (aller → futur)",
        answer: 'irons',
        accepted_alternatives: ['irons'],
      },
      {
        type: 'cloze',
        prompt: 'Il ____ beau ce week-end. (faire → futur)',
        answer: 'fera',
        accepted_alternatives: ['fera'],
      },
    ],
  },

  {
    level: 'B1',
    slug: 'b1-conditionnel',
    title_en: 'The Conditional: Le Conditionnel',
    title_fr: 'Le conditionnel présent',
    theme: 'grammar',
    grammar_focus: 'conditionnel présent; politeness and hypothesis',
    description:
      'Say what you "would" do, make polite requests, and express wishes. The conditionnel reuses the future stem with imperfect endings.',
    lessons: [
      {
        type: 'grammar',
        title: 'Future stem + imperfect endings',
        body_markdown: [
          '## A tense you already half-know',
          '',
          'The **conditionnel présent** ("I would speak") takes the **futur simple stem** and adds the **imparfait endings** (-ais, -ais, -ait, -ions, -iez, -aient):',
          '',
          '- je parler**ais** — I would speak',
          '- tu parler**ais** — you would speak',
          '- il/elle parler**ait** — he/she would speak',
          '- nous parler**ions** — we would speak',
          '- vous parler**iez** — you would speak',
          '- ils/elles parler**aient** — they would speak',
          '',
          'The irregular stems are the **same as the futur** (`ser-`, `aur-`, `ir-`, `fer-`, `voudr-`, `pourr-`…): `je serais`, `il ferait`, `nous voudrions`.',
          '',
          '## Three everyday uses',
          '',
          "1. **Politeness** — softening a request: `Je **voudrais** un café.` (I would like a coffee.) · `**Pourriez**-vous m'aider ?` (Could you help me?)",
          "2. **Wishes** — `J'**aimerais** voyager.` (I would like to travel.)",
          '3. **Hypothesis** — the outcome of an *if*: `À ta place, je **partirais**.` (In your place, I would leave.)',
          '',
          'Compare: `je veux` (I want — blunt) vs `je voudrais` (I would like — polite). At B1, the conditionnel is your politeness tool.',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Being polite and hypothetical',
        body_markdown: 'Phrases for polite requests, wishes and softening what you say.',
      },
    ],
    vocab: [
      { lemma_fr: 'aimer', translation_en: 'to like / to love', pos: 'verb', ipa: 'eme' },
      { lemma_fr: 'vouloir', translation_en: 'to want', pos: 'verb', ipa: 'vulwaʁ' },
      {
        lemma_fr: 'pouvoir',
        translation_en: 'to be able to',
        pos: 'verb',
        ipa: 'puvwaʁ',
      },
      {
        lemma_fr: 'devoir',
        translation_en: 'to have to / must',
        pos: 'verb',
        ipa: 'dəvwaʁ',
      },
      {
        lemma_fr: 'un souhait',
        translation_en: 'a wish',
        pos: 'noun',
        gender: 'm',
        ipa: 'œ̃ swɛ',
      },
      { lemma_fr: 'volontiers', translation_en: 'gladly', pos: 'adverb', ipa: 'vɔlɔ̃tje' },
      {
        lemma_fr: "s'il vous plaît",
        translation_en: 'please (formal)',
        pos: 'phrase',
        ipa: 'sil vu plɛ',
      },
      {
        lemma_fr: 'un conseil',
        translation_en: 'a piece of advice',
        pos: 'noun',
        gender: 'm',
        ipa: 'œ̃ kɔ̃sɛj',
      },
      {
        lemma_fr: 'à ta place',
        translation_en: 'in your place',
        pos: 'phrase',
        ipa: 'a ta plas',
      },
      {
        lemma_fr: 'idéalement',
        translation_en: 'ideally',
        pos: 'adverb',
        ipa: 'idealmɑ̃',
      },
      { lemma_fr: 'rêver', translation_en: 'to dream', pos: 'verb', ipa: 'ʁeve' },
    ],
    sentences: [
      {
        text_fr: 'Je voudrais réserver une table pour deux.',
        text_en: 'I would like to book a table for two.',
      },
      {
        text_fr: "Pourriez-vous répéter, s'il vous plaît ?",
        text_en: 'Could you repeat, please?',
      },
      {
        text_fr: "J'aimerais habiter près de la mer.",
        text_en: 'I would like to live near the sea.',
      },
      {
        text_fr: 'À ta place, je prendrais le train.',
        text_en: 'In your place, I would take the train.',
      },
      { text_fr: 'Nous devrions partir plus tôt.', text_en: 'We should leave earlier.' },
      {
        text_fr: 'Elle aimerait apprendre le piano.',
        text_en: 'She would like to learn the piano.',
      },
      { text_fr: "Est-ce que tu pourrais m'aider ?", text_en: 'Could you help me?' },
      { text_fr: 'Ce serait une bonne idée.', text_en: 'That would be a good idea.' },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: "Je ____ un verre d'eau, s'il vous plaît. (vouloir → conditionnel)",
        answer: 'voudrais',
        accepted_alternatives: ['voudrais'],
      },
      {
        type: 'cloze',
        prompt: "____-vous m'aider ? (pouvoir → conditionnel)",
        answer: 'Pourriez',
        accepted_alternatives: ['pourriez', 'Pourriez'],
      },
      {
        type: 'cloze',
        prompt: 'À ta place, je ____ plus tôt. (partir → conditionnel)',
        answer: 'partirais',
        accepted_alternatives: ['partirais'],
      },
    ],
  },

  {
    level: 'B1',
    slug: 'b1-si-hypotheses',
    title_en: 'If-Clauses: Les Phrases avec «si»',
    title_fr: 'Les hypothèses avec «si»',
    theme: 'grammar',
    grammar_focus: 'si-clauses: real (si + présent) and unreal (si + imparfait)',
    description:
      'Build conditions and hypotheses. Learn the two key patterns: si + present for real conditions, and si + imperfect + conditional for imaginary ones.',
    lessons: [
      {
        type: 'grammar',
        title: 'Two patterns with «si»',
        body_markdown: [
          '## Real condition: si + présent',
          '',
          'When the condition is realistic, use **si + présent**, and the result in the **présent**, **futur**, or **impératif**:',
          '',
          '- `Si tu **veux**, on **peut** sortir.` — If you want, we can go out.',
          "- `Si j'**ai** le temps, je te **téléphonerai**.` — If I have time, I will call you.",
          '- `Si tu **es** fatigué, **repose**-toi.` — If you are tired, rest.',
          '',
          '## Unreal / imaginary: si + imparfait → conditionnel',
          '',
          'To imagine something that is **not the case** (now or in general), use **si + imparfait**, and the result in the **conditionnel présent**:',
          '',
          "- `Si j'**avais** de l'argent, je **voyagerais**.` — If I had money, I would travel.",
          '- `Si nous **étions** riches, nous **achèterions** une maison.` — If we were rich, we would buy a house.',
          '',
          '## Never «si» + conditionnel',
          '',
          'A classic mistake: never put the conditionnel **after** *si*. The conditionnel goes in the **other** clause. The order can flip freely:',
          '',
          "`Je voyagerais si j'avais de l'argent.` = `Si j'avais de l'argent, je voyagerais.`",
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Conditions and possibilities',
        body_markdown: 'Words for talking about conditions, chance and consequences.',
      },
    ],
    vocab: [
      { lemma_fr: 'si', translation_en: 'if', pos: 'conjunction', ipa: 'si' },
      {
        lemma_fr: "l'argent",
        translation_en: 'money',
        pos: 'noun',
        gender: 'm',
        ipa: 'laʁʒɑ̃',
      },
      {
        lemma_fr: 'gagner',
        translation_en: 'to win / to earn',
        pos: 'verb',
        ipa: 'ɡaɲe',
      },
      {
        lemma_fr: 'la chance',
        translation_en: 'luck',
        pos: 'noun',
        gender: 'f',
        ipa: 'la ʃɑ̃s',
      },
      {
        lemma_fr: 'possible',
        translation_en: 'possible',
        pos: 'adjective',
        ipa: 'pɔsibl',
      },
      { lemma_fr: 'imaginer', translation_en: 'to imagine', pos: 'verb', ipa: 'imaʒine' },
      {
        lemma_fr: 'une condition',
        translation_en: 'a condition',
        pos: 'noun',
        gender: 'f',
        ipa: 'yn kɔ̃disjɔ̃',
      },
      { lemma_fr: 'sinon', translation_en: 'otherwise', pos: 'adverb', ipa: 'sinɔ̃' },
      {
        lemma_fr: 'le temps libre',
        translation_en: 'free time',
        pos: 'noun',
        gender: 'm',
        ipa: 'lə tɑ̃ libʁ',
      },
      { lemma_fr: 'choisir', translation_en: 'to choose', pos: 'verb', ipa: 'ʃwaziʁ' },
    ],
    sentences: [
      {
        text_fr: 'Si tu veux, on peut aller au cinéma.',
        text_en: 'If you want, we can go to the cinema.',
      },
      {
        text_fr: "Si j'ai le temps, je viendrai demain.",
        text_en: 'If I have time, I will come tomorrow.',
      },
      {
        text_fr: "Si j'étais riche, je voyagerais partout.",
        text_en: 'If I were rich, I would travel everywhere.',
      },
      {
        text_fr: 'Si nous avions une voiture, ce serait plus facile.',
        text_en: 'If we had a car, it would be easier.',
      },
      { text_fr: 'Repose-toi si tu es fatigué.', text_en: 'Rest if you are tired.' },
      {
        text_fr: 'Si elle gagnait au loto, elle achèterait une maison.',
        text_en: 'If she won the lottery, she would buy a house.',
      },
      {
        text_fr: 'Dépêche-toi, sinon nous serons en retard.',
        text_en: 'Hurry up, otherwise we will be late.',
      },
      {
        text_fr: 'Que ferais-tu si tu avais plus de temps libre ?',
        text_en: 'What would you do if you had more free time?',
      },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: "Si j'avais de l'argent, je ____ le monde. (voyager → conditionnel)",
        answer: 'voyagerais',
        accepted_alternatives: ['voyagerais'],
      },
      {
        type: 'cloze',
        prompt: 'Si tu ____ fatigué, repose-toi. (être → présent)',
        answer: 'es',
        accepted_alternatives: ['es'],
      },
      {
        type: 'cloze',
        prompt: 'Si nous ____ riches, nous achèterions une maison. (être → imparfait)',
        answer: 'étions',
        accepted_alternatives: ['étions'],
      },
    ],
  },

  {
    level: 'B1',
    slug: 'b1-subjonctif',
    title_en: 'The Subjunctive: Le Subjonctif',
    title_fr: 'Le subjonctif présent',
    theme: 'grammar',
    grammar_focus: 'subjonctif présent; triggers of necessity, will, emotion, doubt',
    description:
      'The mood of necessity, wish, emotion and doubt. Learn to form the subjonctif and to recognise the expressions that trigger it.',
    lessons: [
      {
        type: 'grammar',
        title: 'Forming and triggering the subjonctif',
        body_markdown: [
          '## The forms',
          '',
          'For most verbs, take the **ils/elles** form of the present, drop **-ent**, and add **-e, -es, -e, -ions, -iez, -ent**:',
          '',
          "- que je parl**e**, que tu parl**es**, qu'il parl**e**",
          "- que nous parl**ions**, que vous parl**iez**, qu'ils parl**ent**",
          '',
          'A few very common verbs are irregular:',
          '',
          '- être → que je **sois**, que nous **soyons**',
          "- avoir → que j'**aie**, que nous **ayons**",
          "- aller → que j'**aille**, faire → que je **fasse**",
          '- pouvoir → que je **puisse**, savoir → que je **sache**, vouloir → que je **veuille**',
          '',
          '## When to use it',
          '',
          'The subjonctif appears in a subordinate clause after **que**, triggered by an expression of:',
          '',
          '- **Necessity** — `Il faut que tu **viennes**.` (You must come.)',
          "- **Will / wish** — `Je veux qu'il **parte**.` (I want him to leave.)",
          "- **Emotion** — `Je suis content que tu **sois** là.` (I'm glad you're here.)",
          "- **Doubt** — `Je ne pense pas qu'il **ait** raison.` (I don't think he's right.)",
          '- **Certain conjunctions** — `bien que`, `pour que`, `avant que`, `à condition que`.',
          '',
          "After certainty (`je pense que`, `je sais que`) you keep the **indicative**: `Je pense qu'il **a** raison.`",
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Expressions that trigger the subjunctive',
        body_markdown:
          'The verbs and phrases that are usually followed by «que» + subjonctif.',
      },
    ],
    vocab: [
      {
        lemma_fr: 'il faut que',
        translation_en: 'it is necessary that',
        pos: 'phrase',
        ipa: 'il fo kə',
      },
      {
        lemma_fr: 'vouloir que',
        translation_en: 'to want that',
        pos: 'phrase',
        ipa: 'vulwaʁ kə',
      },
      {
        lemma_fr: 'bien que',
        translation_en: 'although',
        pos: 'conjunction',
        ipa: 'bjɛ̃ kə',
      },
      {
        lemma_fr: 'pour que',
        translation_en: 'so that',
        pos: 'conjunction',
        ipa: 'puʁ kə',
      },
      {
        lemma_fr: 'avoir peur que',
        translation_en: 'to be afraid that',
        pos: 'phrase',
        ipa: 'avwaʁ pœʁ kə',
      },
      {
        lemma_fr: 'être content que',
        translation_en: 'to be happy that',
        pos: 'phrase',
        ipa: 'ɛtʁ kɔ̃tɑ̃ kə',
      },
      { lemma_fr: 'douter', translation_en: 'to doubt', pos: 'verb', ipa: 'dute' },
      {
        lemma_fr: 'nécessaire',
        translation_en: 'necessary',
        pos: 'adjective',
        ipa: 'neseseʁ',
      },
      {
        lemma_fr: 'important',
        translation_en: 'important',
        pos: 'adjective',
        ipa: 'ɛ̃pɔʁtɑ̃',
      },
      { lemma_fr: 'souhaiter', translation_en: 'to wish', pos: 'verb', ipa: 'swɛte' },
    ],
    sentences: [
      {
        text_fr: 'Il faut que tu fasses tes devoirs.',
        text_en: 'You have to do your homework.',
      },
      { text_fr: 'Je veux que tu sois heureux.', text_en: 'I want you to be happy.' },
      {
        text_fr: "Il est important que nous soyons à l'heure.",
        text_en: 'It is important that we are on time.',
      },
      {
        text_fr: "Bien qu'il pleuve, nous sortons.",
        text_en: 'Although it is raining, we are going out.',
      },
      {
        text_fr: 'Je suis content que vous soyez venus.',
        text_en: 'I am glad that you came.',
      },
      {
        text_fr: "Je ne pense pas qu'il ait raison.",
        text_en: "I don't think he is right.",
      },
      {
        text_fr: "Il faut que j'aille chez le médecin.",
        text_en: 'I have to go to the doctor.',
      },
      {
        text_fr: 'Elle travaille pour que ses enfants réussissent.',
        text_en: 'She works so that her children succeed.',
      },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: 'Il faut que tu ____ tes devoirs. (faire → subjonctif)',
        answer: 'fasses',
        accepted_alternatives: ['fasses'],
      },
      {
        type: 'cloze',
        prompt: "Je veux que vous ____ à l'heure. (être → subjonctif)",
        answer: 'soyez',
        accepted_alternatives: ['soyez'],
      },
      {
        type: 'cloze',
        prompt: "Il faut que j'____ chez le médecin. (aller → subjonctif)",
        answer: 'aille',
        accepted_alternatives: ['aille'],
      },
    ],
  },

  {
    level: 'B1',
    slug: 'b1-pronoms-relatifs',
    title_en: 'Relative Pronouns: qui, que, dont, où',
    title_fr: 'Les pronoms relatifs',
    theme: 'grammar',
    grammar_focus: 'relative pronouns qui / que / dont / où',
    description:
      'Join two ideas into one smoother sentence. Learn when to use qui (subject), que (object), dont (of/about), and où (where/when).',
    lessons: [
      {
        type: 'grammar',
        title: 'qui, que, dont, où',
        body_markdown: [
          '## Connecting sentences',
          '',
          "A relative pronoun links a noun to a clause that describes it, so you don't repeat the noun.",
          '',
          "- **qui** = **subject** of the clause (does the action): `C'est le train **qui** part à midi.` (the train **that** leaves at noon)",
          "- **que** = **direct object** of the clause: `C'est le livre **que** je lis.` (the book **that** I am reading)",
          "- **dont** = replaces **de + noun** (of/about/whose): `C'est le film **dont** je parle.` (the film I'm talking **about**) · `la femme **dont** le fils…` (the woman **whose** son…)",
          "- **où** = **place or time**: `la ville **où** j'habite` (the city **where** I live) · `le jour **où** on s'est rencontrés` (the day **when** we met)",
          '',
          '## qui vs que — the key test',
          '',
          "If the pronoun is **followed by a verb**, use **qui**. If it's followed by a **subject (noun/pronoun)**, use **que**:",
          '',
          '- `le gâteau **qui** est sur la table` (qui + verb)',
          '- `le gâteau **que** tu as fait` (que + subject "tu")',
          '',
          "Note **que → qu'** before a vowel; **qui** never elides: `l'ami qu'il aime`, but `l'ami qui arrive`.",
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Describing people and things',
        body_markdown:
          'Useful nouns and verbs to practise joining clauses with relative pronouns.',
      },
    ],
    vocab: [
      {
        lemma_fr: 'qui',
        translation_en: 'who / that (subject)',
        pos: 'pronoun',
        ipa: 'ki',
      },
      {
        lemma_fr: 'que',
        translation_en: 'that / which (object)',
        pos: 'pronoun',
        ipa: 'kə',
      },
      { lemma_fr: 'dont', translation_en: 'of which / whose', pos: 'pronoun', ipa: 'dɔ̃' },
      { lemma_fr: 'où', translation_en: 'where / when', pos: 'pronoun', ipa: 'u' },
      {
        lemma_fr: 'un endroit',
        translation_en: 'a place',
        pos: 'noun',
        gender: 'm',
        ipa: 'œ̃ nɑ̃dʁwa',
      },
      {
        lemma_fr: 'un souvenir',
        translation_en: 'a memory',
        pos: 'noun',
        gender: 'm',
        ipa: 'œ̃ suvniʁ',
      },
      {
        lemma_fr: 'connaître',
        translation_en: 'to know (be familiar with)',
        pos: 'verb',
        ipa: 'kɔnɛtʁ',
      },
      { lemma_fr: 'rencontrer', translation_en: 'to meet', pos: 'verb', ipa: 'ʁɑ̃kɔ̃tʁe' },
      {
        lemma_fr: 'un objet',
        translation_en: 'an object',
        pos: 'noun',
        gender: 'm',
        ipa: 'œ̃ nɔbʒɛ',
      },
      {
        lemma_fr: 'préféré',
        translation_en: 'favourite',
        pos: 'adjective',
        ipa: 'pʁefeʁe',
      },
    ],
    sentences: [
      {
        text_fr: "C'est le train qui part à midi.",
        text_en: 'It is the train that leaves at noon.',
      },
      {
        text_fr: 'Voici le livre que je lis en ce moment.',
        text_en: 'Here is the book that I am reading right now.',
      },
      {
        text_fr: "C'est le film dont je t'ai parlé.",
        text_en: 'It is the film that I told you about.',
      },
      {
        text_fr: "La ville où j'habite est petite.",
        text_en: 'The city where I live is small.',
      },
      {
        text_fr: 'Je connais une femme dont le fils est acteur.',
        text_en: 'I know a woman whose son is an actor.',
      },
      {
        text_fr: 'Le jour où nous nous sommes rencontrés, il pleuvait.',
        text_en: 'The day we met, it was raining.',
      },
      {
        text_fr: "C'est un ami que j'aime beaucoup.",
        text_en: 'He is a friend that I like a lot.',
      },
      {
        text_fr: "L'endroit qui me plaît le plus, c'est la plage.",
        text_en: 'The place I like most is the beach.',
      },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: "C'est le train ____ part à midi. (relatif)",
        answer: 'qui',
        accepted_alternatives: ['qui'],
      },
      {
        type: 'cloze',
        prompt: 'Voici le livre ____ je lis. (relatif)',
        answer: 'que',
        accepted_alternatives: ['que'],
      },
      {
        type: 'cloze',
        prompt: "La ville ____ j'habite est petite. (relatif)",
        answer: 'où',
        accepted_alternatives: ['où', 'ou'],
      },
    ],
  },

  {
    level: 'B1',
    slug: 'b1-plus-que-parfait',
    title_en: 'The Past Before the Past: Le Plus-que-parfait',
    title_fr: 'Le plus-que-parfait',
    theme: 'grammar',
    grammar_focus: 'plus-que-parfait; an action before another past action',
    description:
      'Talk about what had already happened before another past moment. Learn the plus-que-parfait: imperfect of avoir/être plus a past participle.',
    lessons: [
      {
        type: 'grammar',
        title: 'Forming the plus-que-parfait',
        body_markdown: [
          '## The "past of the past"',
          '',
          'The **plus-que-parfait** describes an action **completed before** another past action ("I had eaten"). It is built like the passé composé, but with the auxiliary in the **imparfait**:',
          '',
          '**imparfait of avoir/être + past participle**',
          '',
          "- j'**avais** mangé — I had eaten",
          '- tu **avais** fini — you had finished',
          '- il **était** parti — he had left',
          '- nous **étions** arrivés — we had arrived',
          '',
          '## Same auxiliary rules as the passé composé',
          '',
          'The verbs that take **être** in the passé composé (movement/change of state) also take **être** here, and the participle **agrees** with the subject:',
          '',
          '`Elle était déjà partie.` · `Ils étaient venus.`',
          '',
          "## Why it's useful",
          '',
          'It sets the earlier of two past events:',
          '',
          '`Quand je suis arrivé, le film **avait** déjà **commencé**.`',
          '(When I arrived, the film had already started.)',
          '',
          'Time words that often appear with it: **déjà** (already), **ne… pas encore** (not yet), **avant** (before), **la veille** (the day before).',
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Ordering events in the past',
        body_markdown: 'Time markers and verbs for saying what had happened earlier.',
      },
    ],
    vocab: [
      { lemma_fr: 'déjà', translation_en: 'already', pos: 'adverb', ipa: 'deʒa' },
      {
        lemma_fr: 'ne… pas encore',
        translation_en: 'not yet',
        pos: 'phrase',
        ipa: 'nə pa ɑ̃kɔʁ',
      },
      {
        lemma_fr: 'la veille',
        translation_en: 'the day before',
        pos: 'noun',
        gender: 'f',
        ipa: 'la vɛj',
      },
      {
        lemma_fr: 'auparavant',
        translation_en: 'beforehand',
        pos: 'adverb',
        ipa: 'opaʁavɑ̃',
      },
      { lemma_fr: 'oublier', translation_en: 'to forget', pos: 'verb', ipa: 'ublije' },
      { lemma_fr: 'partir', translation_en: 'to leave', pos: 'verb', ipa: 'paʁtiʁ' },
      { lemma_fr: 'commencer', translation_en: 'to begin', pos: 'verb', ipa: 'kɔmɑ̃se' },
      { lemma_fr: 'terminer', translation_en: 'to finish', pos: 'verb', ipa: 'tɛʁmine' },
      {
        lemma_fr: 'un événement',
        translation_en: 'an event',
        pos: 'noun',
        gender: 'm',
        ipa: 'œ̃ nevɛnmɑ̃',
      },
      { lemma_fr: 'déçu', translation_en: 'disappointed', pos: 'adjective', ipa: 'desy' },
    ],
    sentences: [
      {
        text_fr: 'Quand je suis arrivé, le film avait déjà commencé.',
        text_en: 'When I arrived, the film had already started.',
      },
      {
        text_fr: 'Elle était déjà partie quand tu as téléphoné.',
        text_en: 'She had already left when you called.',
      },
      {
        text_fr: 'Nous avions mangé avant leur arrivée.',
        text_en: 'We had eaten before their arrival.',
      },
      {
        text_fr: "J'avais oublié mon parapluie à la maison.",
        text_en: 'I had forgotten my umbrella at home.',
      },
      {
        text_fr: "Ils n'avaient pas encore vu ce spectacle.",
        text_en: 'They had not yet seen this show.',
      },
      {
        text_fr: 'La veille, il avait beaucoup plu.',
        text_en: 'The day before, it had rained a lot.',
      },
      {
        text_fr: 'Tu étais déjà venu ici auparavant ?',
        text_en: 'Had you already come here before?',
      },
      {
        text_fr: 'Le train était parti quand nous sommes arrivés.',
        text_en: 'The train had left when we arrived.',
      },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: 'Quand je suis arrivé, le film avait déjà ____. (commencer → participe)',
        answer: 'commencé',
        accepted_alternatives: ['commencé'],
      },
      {
        type: 'cloze',
        prompt: 'Elle ____ déjà partie. (être → imparfait)',
        answer: 'était',
        accepted_alternatives: ['était'],
      },
      {
        type: 'cloze',
        prompt: 'Nous ____ mangé avant leur arrivée. (avoir → imparfait)',
        answer: 'avions',
        accepted_alternatives: ['avions'],
      },
    ],
  },

  {
    level: 'B1',
    slug: 'b1-discours-indirect',
    title_en: 'Reported Speech: Le Discours Indirect',
    title_fr: 'Le discours indirect',
    theme: 'grammar',
    grammar_focus: 'reported speech; tense shifts and question words',
    description:
      'Report what other people said. Learn how statements and questions change — the linking words and the tense shifts when the report is in the past.',
    lessons: [
      {
        type: 'grammar',
        title: 'Turning direct speech into reported speech',
        body_markdown: [
          '## Statements → «… que …»',
          '',
          'To report a statement, use a verb like **dire** + **que**:',
          '',
          '- Direct: `Il dit : « Je suis fatigué. »`',
          "- Reported: `Il dit **qu'il est** fatigué.`",
          '',
          '## Questions → si / ce que / ce qui',
          '',
          'Reported questions drop the inversion and the question mark:',
          '',
          '- Yes/no → **si**: `« Tu viens ? »` → `Il demande **si** je viens.`',
          "- *Qu'est-ce que* → **ce que**: `« Que fais-tu ? »` → `Il demande **ce que** je fais.`",
          "- *Qu'est-ce qui* → **ce qui**: `« Qu'est-ce qui se passe ? »` → `Il demande **ce qui** se passe.`",
          '- Other question words stay: `où`, `quand`, `pourquoi`, `comment`.',
          '',
          '## Tense shift when reporting in the past',
          '',
          'If the reporting verb is in the **past** (`il a dit`), the reported tense shifts back:',
          '',
          "- présent → **imparfait**: « Je **pars** » → Il a dit qu'il **partait**.",
          "- passé composé → **plus-que-parfait**: « J'**ai fini** » → Il a dit qu'il **avait fini**.",
          "- futur → **conditionnel**: « Je **viendrai** » → Il a dit qu'il **viendrait**.",
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Reporting what people say',
        body_markdown: 'The verbs and linking words used to report speech.',
      },
    ],
    vocab: [
      { lemma_fr: 'dire', translation_en: 'to say / to tell', pos: 'verb', ipa: 'diʁ' },
      { lemma_fr: 'demander', translation_en: 'to ask', pos: 'verb', ipa: 'dəmɑ̃de' },
      { lemma_fr: 'répondre', translation_en: 'to answer', pos: 'verb', ipa: 'ʁepɔ̃dʁ' },
      {
        lemma_fr: 'expliquer',
        translation_en: 'to explain',
        pos: 'verb',
        ipa: 'ɛksplike',
      },
      { lemma_fr: 'ajouter', translation_en: 'to add', pos: 'verb', ipa: 'aʒute' },
      {
        lemma_fr: 'raconter',
        translation_en: 'to tell (a story)',
        pos: 'verb',
        ipa: 'ʁakɔ̃te',
      },
      {
        lemma_fr: 'ce que',
        translation_en: 'what (object)',
        pos: 'phrase',
        ipa: 'sə kə',
      },
      {
        lemma_fr: 'ce qui',
        translation_en: 'what (subject)',
        pos: 'phrase',
        ipa: 'sə ki',
      },
      {
        lemma_fr: 'une nouvelle',
        translation_en: 'a piece of news',
        pos: 'noun',
        gender: 'f',
        ipa: 'yn nuvɛl',
      },
      {
        lemma_fr: 'selon',
        translation_en: 'according to',
        pos: 'preposition',
        ipa: 'səlɔ̃',
      },
    ],
    sentences: [
      { text_fr: "Il dit qu'il est fatigué.", text_en: 'He says that he is tired.' },
      {
        text_fr: 'Elle demande si tu viens ce soir.',
        text_en: 'She asks if you are coming tonight.',
      },
      {
        text_fr: 'Je ne sais pas ce que tu veux.',
        text_en: "I don't know what you want.",
      },
      {
        text_fr: "Il a dit qu'il partait le lendemain.",
        text_en: 'He said that he was leaving the next day.',
      },
      {
        text_fr: "Elle a répondu qu'elle avait déjà fini.",
        text_en: 'She answered that she had already finished.',
      },
      {
        text_fr: "Ils ont expliqué qu'ils viendraient plus tard.",
        text_en: 'They explained that they would come later.',
      },
      { text_fr: 'Demande-lui ce qui se passe.', text_en: 'Ask him what is happening.' },
      {
        text_fr: 'Selon lui, le musée est fermé le lundi.',
        text_en: 'According to him, the museum is closed on Mondays.',
      },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: 'Il dit ____ il est fatigué. (mot de liaison)',
        answer: "qu'",
        accepted_alternatives: ["qu'", 'que', 'qu'],
      },
      {
        type: 'cloze',
        prompt: 'Elle demande ____ tu viens. (question oui/non)',
        answer: 'si',
        accepted_alternatives: ['si'],
      },
      {
        type: 'cloze',
        prompt: "Il a dit qu'il ____ le lendemain. (partir → imparfait)",
        answer: 'partait',
        accepted_alternatives: ['partait'],
      },
    ],
  },

  {
    level: 'B1',
    slug: 'b1-gerondif-connecteurs',
    title_en: 'Linking Ideas: Le Gérondif & Connecteurs',
    title_fr: 'Le gérondif et les connecteurs',
    theme: 'grammar',
    grammar_focus: 'gérondif (en + -ant); logical connectors and expressing opinion',
    description:
      'Express two actions at once and connect your ideas like a fluent speaker. Learn the gérondif and the logical connectors for cause, consequence and contrast.',
    lessons: [
      {
        type: 'grammar',
        title: 'The gérondif and connecting words',
        body_markdown: [
          '## Le gérondif : en + -ant',
          '',
          'The gérondif expresses an action happening **at the same time** as (or **by means of**) another, when both have the **same subject**. Form it from the **nous** present stem + **-ant**, with **en**:',
          '',
          '- parler → `en parlant` · finir → `en finissant` · faire → `en faisant`',
          '- Irregulars: être → `en étant`, avoir → `en ayant`, savoir → `en sachant`',
          '',
          '- `Il chante **en travaillant**.` — He sings while working.',
          '- `**En étudiant** chaque jour, tu progresseras.` — By studying every day, you will progress.',
          '',
          '## Connecteurs logiques',
          '',
          'These link your ideas so you sound fluent, not choppy:',
          '',
          '- **Cause**: `parce que`, `car`, `puisque` (since), `grâce à` (thanks to)',
          "- **Consequence**: `donc` (so), `alors`, `c'est pourquoi`",
          '- **Contrast**: `mais`, `pourtant` (yet), `cependant` (however), `bien que` (+ subjonctif)',
          "- **Adding / ordering**: `d'abord`, `ensuite`, `enfin`, `de plus` (moreover)",
          '',
          '## Giving your opinion',
          '',
          "Open with: `À mon avis…`, `Je pense que…`, `Selon moi…`, `Il me semble que…` — then support it with a connector: `Je pense que c'est utile **parce que**…`.",
        ].join('\n'),
      },
      {
        type: 'vocab',
        title: 'Connectors and opinion phrases',
        body_markdown:
          'The linking words and opinion openers that make your French flow.',
      },
    ],
    vocab: [
      {
        lemma_fr: 'en même temps',
        translation_en: 'at the same time',
        pos: 'phrase',
        ipa: 'ɑ̃ mɛm tɑ̃',
      },
      {
        lemma_fr: 'parce que',
        translation_en: 'because',
        pos: 'conjunction',
        ipa: 'paʁs kə',
      },
      {
        lemma_fr: 'donc',
        translation_en: 'so / therefore',
        pos: 'conjunction',
        ipa: 'dɔ̃k',
      },
      {
        lemma_fr: 'pourtant',
        translation_en: 'yet / however',
        pos: 'adverb',
        ipa: 'puʁtɑ̃',
      },
      { lemma_fr: 'cependant', translation_en: 'however', pos: 'adverb', ipa: 'səpɑ̃dɑ̃' },
      { lemma_fr: 'grâce à', translation_en: 'thanks to', pos: 'phrase', ipa: 'ɡʁɑs a' },
      {
        lemma_fr: 'à mon avis',
        translation_en: 'in my opinion',
        pos: 'phrase',
        ipa: 'a mɔ̃ navi',
      },
      {
        lemma_fr: 'selon moi',
        translation_en: 'in my view',
        pos: 'phrase',
        ipa: 'səlɔ̃ mwa',
      },
      {
        lemma_fr: "d'abord",
        translation_en: 'first (of all)',
        pos: 'adverb',
        ipa: 'dabɔʁ',
      },
      { lemma_fr: 'enfin', translation_en: 'finally', pos: 'adverb', ipa: 'ɑ̃fɛ̃' },
      {
        lemma_fr: 'améliorer',
        translation_en: 'to improve',
        pos: 'verb',
        ipa: 'ameljɔʁe',
      },
    ],
    sentences: [
      {
        text_fr: 'Il écoute de la musique en travaillant.',
        text_en: 'He listens to music while working.',
      },
      {
        text_fr: 'En étudiant chaque jour, tu progresseras vite.',
        text_en: 'By studying every day, you will progress quickly.',
      },
      {
        text_fr: 'Je suis fatigué, donc je vais me coucher.',
        text_en: 'I am tired, so I am going to bed.',
      },
      {
        text_fr: 'Il pleut, pourtant ils sortent.',
        text_en: 'It is raining, yet they are going out.',
      },
      {
        text_fr: "J'ai réussi grâce à ton aide.",
        text_en: 'I succeeded thanks to your help.',
      },
      {
        text_fr: 'À mon avis, ce film est excellent.',
        text_en: 'In my opinion, this film is excellent.',
      },
      {
        text_fr: "D'abord nous mangeons, ensuite nous partons.",
        text_en: 'First we eat, then we leave.',
      },
      {
        text_fr: "Elle apprend le français parce qu'elle aime la culture.",
        text_en: 'She is learning French because she loves the culture.',
      },
    ],
    exercises: [
      {
        type: 'cloze',
        prompt: 'Il chante en ____. (travailler → gérondif, sans « en »)',
        answer: 'travaillant',
        accepted_alternatives: ['travaillant'],
      },
      {
        type: 'cloze',
        prompt: 'Je suis fatigué, ____ je vais me coucher. (conséquence)',
        answer: 'donc',
        accepted_alternatives: ['donc'],
      },
      {
        type: 'cloze',
        prompt: "J'ai réussi ____ ton aide. (cause)",
        answer: 'grâce à',
        accepted_alternatives: ['grâce à', 'grace a'],
      },
    ],
  },
];
